# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: precise
language: cpp

branches:

  only:
    - master
    - ApplicationServer

notifications:
    email: false
    slack:
      rooms:
        - tallerii-2c-2016:GGcOHSrhyXYsoUGETyThlbcC#general
        - tallerii-2c-2016:GGcOHSrhyXYsoUGETyThlbcC#plandetrabajo
      on_success: change
      on_failure: always
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

services:
  - docker
  
before_install:
  - docker build -t appserverimg ApplicationServer/
  - docker build -t testingappserverimg ApplicationServer/test
  
script:

  - docker run --name appserver -p 8000:8000 appserverimg & 
  - docker run --name testingappserver --link appserver:appserverhost -ti testingappserverimg;

 # - mkdir build
 # - cd build
 # - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make install && make test