env:
  global:
  - DOCKER_VERSION="1.9.1-0~trusty"



sudo: required

services:
  - docker

before_install:
- sudo docker-compose -f SharedServer/docker-compose.yml build
- sudo docker build -t sharedservertest SharedServer/tests/
- sudo docker-compose -f SharedServer/docker-compose.yml up -d db 

script:
- sleep 10
- sudo docker-compose -f SharedServer/docker-compose.yml up -d 
- sudo docker ps -a
- sudo docker exec -itd sharedserver_sharedserver_1 node code/server.js
- sudo docker exec -it sharedserver_sharedserver_1 ps -A

#- sudo docker exec -it sharedserver_sharedserver_1 nodemon -L server.js

#- sudo docker exec -it sharedserver_sharedserver_1 curl localhost
#- sudo docker exec -it sharedserver_sharedserver_1 curl localhost

- curl 127.0.0.1
#- sudo docker run -it sharedservertest bash