env:
  global:
  - DOCKER_VERSION="1.9.1-0~trusty"



sudo: required

services:
  - docker

before_install:
- sudo docker-compose -f SharedServer/docker-compose.yml build
- sudo docker-compose -f SharedServer/docker-compose.yml up -d 
- sudo docker build -t sharedservertest SharedServer/tests/

script:
- sudo docker ps -a
- sudo docker exec -it sharedserver_sharedserver_1 ps -A

- sudo docker exec -it sharedserver_sharedserver_1 curl localhost
# - curl 127.0.0.1
#- sudo docker run -it sharedservertest bash