# Use new trusty images, should yield newer compilers and packages
sudo: required

services:
  - docker

branches:

  only:
    - master
    - ApplicationServer
    - PruebasDeBusqueda

notifications:
    email: false
    slack:
      rooms:
        - tallerii-2c-2016:GGcOHSrhyXYsoUGETyThlbcC#commit
        - tallerii-2c-2016:GGcOHSrhyXYsoUGETyThlbcC#appser
        
      on_success: change
      on_failure: never

  
before_install:
  # Creates docker image from Dockerfile called "appserverimg" on the local machine.
  - docker build -t appserverimg .
  - docker images #To verify that the new images are on the local host.
  
script:

  # Creates dockers from docker images

  # -d: tells Docker to run the container in the background
  # -p: tells Docker to map port:8000 of the container to our  local port 8000
  # appserverimg: we specified an image, that was built previously.
  # appserver: is the name of the container
  - docker run --name appserver -d -p 8000:8000 appserverimg;
  # To see the running container
  # -l: tells Docker to return de details of the last container started.
  - docker ps -l

 # - mkdir build
 # - cd build
 # - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make install && make test
