# Use new trusty images, should yield newer compilers and packages
sudo: required

services:
  - docker

branches:

  only:
    - master
    - ApplicationServer

notifications:
    email: false
    slack:
      rooms:
        - tallerii-2c-2016:GGcOHSrhyXYsoUGETyThlbcC#commit
        - tallerii-2c-2016:GGcOHSrhyXYsoUGETyThlbcC#plandetrabajo
      on_success: change
      on_failure: never

  
before_install:
  
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev
  - docker build -t appserverimg ApplicationServer/
  - docker build -t testingappserverimg ApplicationServer/tests/
  
script:

  - docker run --name appserver -p 8000:8000 appserverimg & 
  - docker run --name testingappserver --link appserver:appserverhost -ti testingappserverimg;

 # - mkdir build
 # - cd build
 # - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make install && make test