env:
  global:
  - DOCKER_VERSION="1.10.1-0~trusty"


sudo: required

services:
  - docker

before_install:
- sudo docker-compose -f SharedServer/docker-compose.yml build
- sudo docker-compose -f SharedServer/docker-compose.yml up -d 
- sudo docker build -t sharedservertest SharedServer/tests/

script:
- curl 127.0.0.1
#- sudo docker run -it sharedservertest bash