sudo: required

services:
  - docker

before_install:
- sudo docker-compose -f SharedServer/docker-compose.yml build
- sudo docker-compose -f SharedServer/docker-compose.yml up -d 
- cd tests/; sudo docker build -t sharedservertest .

script:
- sudo docker run -it sharedservertest bash